title: "Petr Vychopeň"
#logo: TODO
description: "Meet Petr, a passionate advocate for AI's growth and its integration into daily life. A dreamer grounded in reality, he envisions a future where technology enriches humanity."
show_downloads: true
theme: jekyll-theme-minimal
